name: Local Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: self-hosted

    steps:

      - name: Read and increment version
        id: versioning
        run: |
          cd /home/dariusmurk/repos/homelab
          VERSION_FILE="VERSION"
          VERSION=$(cat $VERSION_FILE)
          echo "Current version: $VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "$NEW_VERSION" > $VERSION_FILE
          echo "New version: $NEW_VERSION"

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      

      - name: Build and tag Docker image
        run: |
          cd /home/dariusmurk/repos/homelab
          VERSION=${{ steps.versioning.outputs.version }}

          docker build -t ${{ vars.FRONTEND_IMAGE_NAME }}:$VERSION .
          docker tag ${{ vars.FRONTEND_IMAGE_NAME }}:$VERSION ${{ vars.FRONTEND_IMAGE_NAME }}:latest

      - name: Push Docker image
        run: |
          cd /home/dariusmurk/repos/homelab
          VERSION=${{ steps.versioning.outputs.version }}
          docker push ${{ vars.FRONTEND_IMAGE_NAME }}:$VERSION
          docker push ${{ vars.FRONTEND_IMAGE_NAME }}:latest

      - name: Run Docker container
        run: |
          cd /home/dariusmurk/repos/homelab
          docker run -d -p 3000:3000 --name 'homelab-fe' ${{ vars.FRONTEND_IMAGE_NAME }}:latest
